server:
  port: 9000

cb:
  daily-info:
    request-url: http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx
    curs-on-date-action: http://web.cbr.ru/GetCursOnDateXML
    timeout: 60000

logging.level:
  tnkf.task: DEBUG
  org.springframework.jdbc: TRACE
  org.springframework.ws.client.MessageTracing:
    sent: TRACE
    received: TRACE

jetty:
  maxThreads: 150
  minThreads: 8
  idleTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/testdb
#    username: alsh
#    password: alsh
  hikari:
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 700000
    minimumIdle: 2
    maximumPoolSize: 5