server:
  port: 8080

cb:
  daily-info:
    request-url: http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx
    curs-on-date-action: http://web.cbr.ru/GetCursOnDateXML
    timeout:
      read: 60000
      connection: 60000
    connection:
      max: 10

logging.level:
  tnkf.task: DEBUG
  org.springframework.jdbc: INFO
  org.springframework.ws.client.MessageTracing:
    sent: INFO
    received: INFO

jetty:
  maxThreads: 150
  minThreads: 8
  idleTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: metrics

spring:
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/testdb
#    username: alsh
#    password: alsh
  hikari:
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 700000
    minimumIdle: 2
    maximumPoolSize: 5