server:
  port: 9000

cb:
  daily-info:
    request-url: http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx
    curs-on-date-action: http://web.cbr.ru/GetCursOnDateXML

logging.level:
  tnkf.task: DEBUG
  org.springframework.ws.client.MessageTracing:
    sent: TRACE
    received: TRACE

jetty:
  maxThreads: 150
  minThreads: 8
  idleTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: